apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      run: php-apache

  template:
    metadata:
      labels:
        run: php-apache
    spec:
      nodeName: kind-worker # The particular node is selected to schedule the replica.
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
      #terminationGracePeriodSeconds: 0
      tolerations:
      - key: "key1"
        value: "value1"
        effect: "NoExecute"
