apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  #replicas: 4
  replicas: 6
  selector:
    matchLabels:
      run: nginx
#  strategy:
#    rollingUpdate:
#      maxSurge: 25%
#      maxUnavailable: 25%
#    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
#        resources:
#          limits:
#            cpu: 500m
#          requests:
#            cpu: 200m
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 4
            preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - spot
          - weight: 5
            preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - on-demand
            
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            run: nginx
        maxSkew: 1
        topologyKey: lifecycle
        whenUnsatisfiable: ScheduleAnyway
      - labelSelector:
          matchLabels:
            run: nginx
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
