apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-deployment","namespace":"default"},"spec":{"replicas":6,"selector":{"matchLabels":{"run":"nginx"}},"template":{"metadata":{"labels":{"run":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}],"resources":{"limits":{"cpu":"500m"},"requests":{"cpu":"200m"}}}]}}}}
  creationTimestamp: "2023-03-18T02:35:23Z"
  generation: 6
  name: nginx-deployment
  namespace: default
  resourceVersion: "1194586"
  uid: 8c611d1c-add5-444f-8937-16f0f3b23c1b
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - spot
            weight: 4
          - preference:
              matchExpressions:
              - key: lifecycle
                operator: In
                values:
                - on-demand
            weight: 5
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            foo: bar
        maxSkew: 1
        topologyKey: lifecycle
        whenUnsatisfiable: ScheduleAnyway
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-03-18T02:35:23Z"
    lastUpdateTime: "2023-03-23T00:28:51Z"
    message: ReplicaSet "nginx-deployment-7c4cdc74b5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-03-23T00:55:14Z"
    lastUpdateTime: "2023-03-23T00:55:14Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 6
  readyReplicas: 2
  replicas: 4
  unavailableReplicas: 2
  updatedReplicas: 4
