apiVersion: v1
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemovePodsViolatingTopologySpreadConstraint":
         enabled: true
         params:
           includeSoftConstraints: true
      "RemoveDuplicates":
         enabled: false
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "RemovePodsViolatingNodeAffinity":
         enabled: false
      "RemovePodsViolatingNodeTaints":
         enabled: false
      "LowNodeUtilization":
         enabled: false
         params:
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 20
               "memory": 20
               "pods": 20
             targetThresholds:
               "cpu" : 50
               "memory": 50
               "pods": 50
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.yaml":"apiVersion: \"descheduler/v1alpha1\"\nkind: \"DeschedulerPolicy\"\nstrategies:\n  \"RemoveDuplicates\":\n     enabled: true\n  \"RemovePodsViolatingInterPodAntiAffinity\":\n     enabled: true\n  \"LowNodeUtilization\":\n     enabled: true\n     params:\n       nodeResourceUtilizationThresholds:\n         thresholds:\n           \"cpu\" : 20\n           \"memory\": 20\n           \"pods\": 20\n         targetThresholds:\n           \"cpu\" : 50\n           \"memory\": 50\n           \"pods\": 50\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"descheduler-policy-configmap","namespace":"kube-system"}}
  creationTimestamp: "2023-03-22T02:53:27Z"
  name: descheduler-policy-configmap
  namespace: kube-system
  resourceVersion: "1187047"
  uid: 19b4ec97-1aba-4a63-8332-c3d9dbaf543c
