apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      # nodeName: three-worker-cluster-worker # The particular node is selected to schedule the replica.
      nodeName: kind-worker # The particular node is selected to schedule the replica.
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
