apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: background-2
  template:
    metadata:
      labels:
        run: background-2
    spec:
      nodeName: kind-worker3
      containers:
      - image: nginx:1.14.2
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 5000m
#          limits:
#            cpu: 1000m
