apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: 2
  selector:
    matchLabels:
      run: php-apache
  template:
    metadata:
      labels:
        run: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        securityContext:
            capabilities:
              add:
                - NET_ADMIN
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

#      topologySpreadConstraints:
#      - maxSkew: 1
#        topologyKey: zone
#        whenUnsatisfiable: DoNotSchedule
#        labelSelector:
#          matchLabels:
#            run: php-apache
#      - maxSkew: 1
#        topologyKey: node
#        whenUnsatisfiable: DoNotSchedule
#        labelSelector:
#          matchLabels:
#            run: php-apache
